# permissions for end users to view jupyterlabs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterlab-viewer-role
rules:
- apiGroups:
  - jupyter.example.com
  resources:
  - jupyterlabs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jupyter.example.com
  resources:
  - jupyterlabs/status
  verbs:
  - get
